### ISSUE TITLE
Implement debug symbol checking

### ISSUE THREAD

**Issue by dothebart** [arangodb/release-test-automation#27]
* create a `install_debug_package` in the release_tester/arangodb/installers/base.py which you implement for now in `.deb` that installs the debug package
* add a new class inbetween [`InstallerBase`](https://github.com/arangodb/release-test-automation/blob/master/release_tester/arangodb/installers/base.py#L112) and [`InstallerDeb`](https://github.com/arangodb/release-test-automation/blob/master/release_tester/arangodb/installers/deb.py#L18) 
  * implement it in `release_tester/arangodb/installers/linux.py`
  * name it `InstallerLinux(InstallerBase)`  => `InstallerDeb(InstallerLinux)` So: 
     * OLD: `InstallerDeb` directly derives `InstallerBase`
     * NEW: `InstallerDeb` derives `InstallerLinux` which in term derives `InstallerBase`
  * add a method to it, that uses GDB to check whether the debug symbols are properly installed using pexpect
  * This method should be `pass` in the base class, hence do nothing. 
  * if the debug symbols can't be found, let the GDB-Subprocess exit, and raise an exception.
* Next these new code needs to be linked into the control flow in [`class Runner`](https://github.com/arangodb/release-test-automation/blob/master/release_tester/arangodb/starter/deployments/runner.py#L109)
   * Invoke the debug symbols install function at the end of [`if self.do_install:`](https://github.com/arangodb/release-test-automation/blob/master/release_tester/arangodb/starter/deployments/runner.py#L114), save its return value to the configuration using `self.cfg.have_debug_package`
  * add the function to test for the debug symbols using gdb in [`if self.do_system_test:`](https://github.com/arangodb/release-test-automation/blob/master/release_tester/arangodb/starter/deployments/runner.py#L144)
* Add the debug package to the uninstallation flow. (TBC)

**Comment by dothebart** [comment]
now add the RPM implementation.

**Comment by MDAlFattah** [comment]
RPM implementation is also done.

**Comment by dothebart** [comment]
closing as implemented.
